name: viejob_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  dio: ^5.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  image_picker: ^1.2.0
  
  # SỬA VERSION MỚI:
  file_picker: 10.3.3              # chọn file PDF - version mới
  url_launcher: ^6.1.11             # mở URL/file PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/